details = {
    "f": ["name", "Khushaal"],
    "l": ["last", "Nandwani"],
    "e": ["email", "khushaal.nandwani@mail.utoronto.ca"],
    "ph": ["phone", "437 983 7957"],
    "u": ["university", "University of Toronto"],
    "prog": ["Program", "Bachelor's of Science"],
    "maj": ["Major and Minor", "Major in Computer Science and Minors in Economics and Statistics"],
    "pwd": ["password", "PASSWORD"],
    "q": ["quit the program"],
    "a": ["address", "450 Front Street West"],
    "c": ["city", "Toronto"],
    "cn": ["country", "Canada"],
    "p": ["postal code", "M5V 0V7"],
    "ld": ["linkedin", "https://www.linkedin.com/in/khushaal-nandwani-375b9191/"],
    "k": ["personal site", "www.khushaal.com"],
    "s": ["salary", "65,000 CAD per year"],
    "eligib": ["what makes you good the role", "I have worked as a software developer co op in the past for a full year. I can adopt to new technologies quickly and write clean code. Most of all, I am someone easy to collaborate with, I also bring an amiable person to the organisation."],
    "goal": ["goal", "I like software developing and working with new people. And I will be doing both of these when I join. As far as long term goal concerns, I do not have any at the moment. "],
    "lm": ["linkedin message", "Hi ", ",\nI am Khushaal, soon graduating from the University of Toronto, with more than an year of professional experience in Software Development. I saw you are the ", " at ", "! hiring developers. I'd love to know how I can be a fit if we can chat!\nThanks:)"],
    "lm2": ["linkedin message 2", "Hey ", ",\nI saw you are the ", " at ", ", a company I'd love to work in. I was wondering if your team needs a young developer and if and how I can be a fit?\nThanks so much!\nKhushaal"],
    "gh": ["github", "https://github.com/khushaal-nandwani"],
    "jt": ["job title", "Software Developer Co-Op"],
    "comp": ["company", "ExperiencePoint"],
    "loc": ["location", "Toronto, ON"],
    "role": ["role description", "Frontend Development: Led frontend development of a web app for clients to book workshops using Angular. Employed ReactiveForms, NgRx, Cypress, Karma, and Jasmine\nData Analysis: Analyzed company’s sales data to answer pressing questions of product owners and determine characteristics of profitable customers using Pandas, NumPy, and Plotly over a dataset of 10,000+ entries.\nProduct Development: Developed one of the core products using Angular, Nest, Automerge, Tailwind, Symfony PHP technologies in an agile environment.\nTesting: Wrote well-documented end-to-end tests for an internal webapp in PHP Symfony Web App, along with Jest unit tests for Nest backend framework and automation tests using Cypress for other products.\nWebsite Maintenance: Developed and maintained the company’s website using WordPress and Hubspot"],
    "jt2": ["job title 2", "DevOps and Software Developer"],
    "comp2": ["company 2", "Tripta Innovations Pvt Ltd"],
    "loc2": ["location 2", "Surat, India"],
    "role2": ["role description 2", "Dev Workflow: Setted up the dev workflow using git hooks, Jira on Windows Server via 3 channels\nProxy Server: Created a proxy server using Python and Flask to monitor the network traffic of the company’s internal webapp.\nWeb App Development: Completely developed a web app from ground up for the company’s internal customer requests management using Angular, SQL Server, and C#.\nDesktop Automation Testing: Increased the speed of the company’s automation testing using AutoIt by over 7 times. Created the framework, designed, and led the testing team in writing tests for the acounting software."],
    "me": ["Qualities", "I am focused, gets the job done. And most of all, genuinely love software development. As a result, I focus on writing clean and sustainable code, which I feel is a rare skill to find. I research well and learn the things quickly, needed for a task assigned to me. "]
}